codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "!test/"
          - "!**/*_test.go"
        
      frontend:
        target: 85%
        threshold: 2%
        paths:
          - "static/**/*.js"
          - "!static/**/*.test.js"
          - "!static/**/*.spec.js"
        
      backend:
        target: 80%
        threshold: 2%
        paths:
          - "**/*.go"
          - "!**/*_test.go"
          - "!test_*.go"
    
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: false

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  
flags:
  frontend:
    paths:
      - static/
    carryforward: false
    
  backend:
    paths:
      - "*.go"
    carryforward: false

ignore:
  - "**/*_test.go"
  - "test_*.go"
  - "test/**"
  - "vendor/**"
  - "node_modules/**"
  - "coverage/**"
  - "dist/**"
  - "build/**"
  - "*.pb.go"
  - "*.pb.gw.go"
  - "mock_*.go"