# golangci-lint configuration
# Documentation: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - node_modules
    - .git
  skip-files:
    - ".*_test.go"
    - "test_.*\\.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Core linters (well-supported across versions)
    - errcheck      # Checking for unchecked errors
    - govet         # Go vet examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Staticcheck
    - unused        # Checks for unused code

    # Additional quality linters
    - bodyclose     # Checks HTTP response body is closed
    - gocognit      # Computes cognitive complexity
    - goconst       # Finds repeated strings
    - gocritic      # Provides many useful checks
    - gocyclo       # Computes cyclomatic complexity
    - gosec         # Security checks
    - misspell      # Finds misspelled words
    - revive        # Fast, configurable linter
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters

  disable:
    - depguard      # We don't need to restrict imports
    - exhaustive    # Too strict for switch statements
    - gochecknoglobals # We use some globals for configuration
    - godox         # We allow TODO/FIXME comments
    - lll           # Line length is handled by editor
    - testpackage   # Tests in same package are fine

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*net/http.ResponseWriter).Write
      - (net/http.ResponseWriter).Write

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 70  # Increase threshold for complex handlers

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  gosec:
    excludes:
      - G104 # Unhandled errors - covered by errcheck
      - G304 # File path provided by user - we need this for file operations
    severity: medium
    confidence: medium

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam # Too restrictive
      - rangeValCopy # Performance is not critical for our use case

  revive:
    severity: warning
    # Disable rules that are too noisy for this project
    enable-all-rules: false
    rules:
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all"]

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocognit
        - goconst
        - bodyclose  # WebSocket connections in tests trigger false positives
        - gocritic

    # Exclude helper code and test utilities
    - path: test/helpers/
      linters:
        - all

    # Exclude known issues in vendored code
    - path: vendor/
      linters:
        - all

    # Exclude some specific issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Ignore error checks for fmt.Println and similar
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck

    # Allow certain patterns
    - text: "should have a package comment"
      linters:
        - revive
        - stylecheck

    - text: "don't use an underscore in package name"
      linters:
        - revive
        - stylecheck

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  fix: false

severity:
  default-severity: warning
  case-sensitive: false