# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$

      - id: go-imports
        name: go imports
        entry: goimports
        language: system
        args: [-w]
        files: \.go$

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        args: [run, --no-config]
        files: \.go$

      - id: go-test
        name: go test
        entry: go
        language: system
        args: [test, -v, ./...]
        files: \.go$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files